// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0TFLB_0qBCyqv8w-EhYmaT0thrBuCP4w',
    appId: '1:236116000088:android:978c211f47a4ce1042392d',
    messagingSenderId: '236116000088',
    projectId: 'tetrofit',
    storageBucket: 'tetrofit.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbsG4hFQpHiXM3Y5wKEauFeht_iGzKWro',
    appId: '1:236116000088:web:2f1f95d0da4206f442392d',
    messagingSenderId: '236116000088',
    projectId: 'tetrofit',
    authDomain: 'tetrofit.firebaseapp.com',
    storageBucket: 'tetrofit.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6tz3p-gr5S-19y7X9-xBZDRP6y44jfVk',
    appId: '1:236116000088:ios:f9dbe39869b3a53142392d',
    messagingSenderId: '236116000088',
    projectId: 'tetrofit',
    storageBucket: 'tetrofit.firebasestorage.app',
    iosBundleId: 'com.example.aaTeris',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6tz3p-gr5S-19y7X9-xBZDRP6y44jfVk',
    appId: '1:236116000088:ios:f9dbe39869b3a53142392d',
    messagingSenderId: '236116000088',
    projectId: 'tetrofit',
    storageBucket: 'tetrofit.firebasestorage.app',
    iosBundleId: 'com.example.aaTeris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbsG4hFQpHiXM3Y5wKEauFeht_iGzKWro',
    appId: '1:236116000088:web:df8fc7bbe3bead7f42392d',
    messagingSenderId: '236116000088',
    projectId: 'tetrofit',
    authDomain: 'tetrofit.firebaseapp.com',
    storageBucket: 'tetrofit.firebasestorage.app',
  );

}