import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    // START: FlutterFire Configuration
    id("com.google.gms.google-services")
    // END: FlutterFire Configuration
    id("org.jetbrains.kotlin.android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "com.retrotrix.tetrofit"
    compileSdk = 35
    ndkVersion = "27.0.12077973"

    val keystorePropertiesFile = rootProject.file("key.properties")
    val keystoreProperties = Properties()
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))

    signingConfigs {
        create("release") {
            keyAlias = keystoreProperties["keyAlias"] as String
            keyPassword = keystoreProperties["keyPassword"] as String
            storeFile = file(keystoreProperties["storeFile"] as String)
            storePassword = keystoreProperties["storePassword"] as String
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.retrotrix.tetrofit"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = 21
        targetSdk = 34
        versionCode = 6
        versionName = "1.1.0"

        // Bật tạo debug symbols
        ndk {
            debugSymbolLevel = "FULL"
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("release")
            // Bật minify và shrink resources
            isMinifyEnabled = true
            isShrinkResources = true
            // Thêm các rules cho proguard
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
                "proguard-flutter.pro"
            )
            // Bật source maps
            isDebuggable = false
            isJniDebuggable = false
            isRenderscriptDebuggable = false
            // Tạo mapping file
            isCrunchPngs = true
        }
        debug {
            // Cấu hình cho debug build
            isDebuggable = true
            isJniDebuggable = true
            isRenderscriptDebuggable = true
            // Tạo source maps cho debug
            // applicationIdSuffix = ".debug"
            // versionNameSuffix = "-debug"
        }
    }

    // Bật tạo native debug symbols
    packagingOptions {
        jniLibs {
            useLegacyPackaging = false
            keepDebugSymbols += "**/*.so"
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
    implementation("com.google.android.play:app-update:2.1.0")
    implementation("com.google.android.play:app-update-ktx:2.1.0")
}

// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----